### ISSUE TITLE
wrong python call

### ISSUE THREAD

**Issue by aueb** [markqvist/rnodeconfigutil#13]
```
[2022-05-15 16:04:05] Firmware extracted
[2022-05-15 16:04:05] Flashing RNode firmware to device on /dev/ttyACM0
/usr/bin/env: »python“: Datei oder Verzeichnis nicht gefunden
```
during autoinstall

python3 would work, where can i change this?

**Comment by markqvist** [comment]
This looks like it is coming from the esp32 flashing tool actually. I can probably just include a modified version of esp-tool.

**Comment by markqvist** [comment]
On further investigation of this, I am not sure what the correct approach here is, since different OSes have different conventions in regards to naming of the python executable. Would you mind sharing what OS this occurred on?

**Comment by markqvist** [comment]
Just as a workaround for now, you should be able to do:

`alias python=python3`

**Comment by markqvist** [comment]
The fix has been implemented in the source of esp-tool, and will be released on PyPi soon.
