### ISSUE TITLE
Custom Sync Word

### ISSUE THREAD

**Issue by rmelgares** [markqvist/rnodeconfigutil#3]
Is it possible to add some feature or functionality to specify a custom sync word? I didn't see an easy way to change this without rebuilding the firmware, since it appears to be hardcoded at the moment. Thanks!

**Comment by markqvist** [comment]
Ok, this is such an old request, and sorry for not getting back to you. If you are still there....

Yes, that will need to be added to the firmware as well, but it is definitely a possibility. Since I am curious, I'd love to know what your use-case is for this feature. Would you mind explaining it?
